baseURL = 'https://akozadaev.github.io/myblog/'
languageCode = "ru-ru"
title = "Персональный блог бэкенд-разработчика"
theme = "PaperMod"

[params]
  author = "akozadaev"
  description = "Заметки разработчика"
  defaultTheme = "auto"  # light/dark/auto

[markup.highlight]
  noClasses = false